/** Public منصة أم كنعان الرقمية home page — opportunity, learning, and WhatsApp conversion. */
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { WHATSAPP_MESSAGES, whatsappHref } from "@/lib/whatsapp";
import { Link } from "wouter";
import { ArrowLeft, ArrowUpLeft, BarChart3, Bot, BriefcaseBusiness, CheckCircle2, ChevronLeft, CircleAlert, ClipboardList, Compass, FileText, GraduationCap, Lightbulb, Menu, MessageCircle, PenTool, Play, Rocket, ShieldCheck, ShoppingBag, Smartphone, Store, Target, UsersRound, X } from "lucide-react";
import { useEffect, useState } from "react";

const fields = [
  { title: "التجارة الإلكترونية", text: "من المنتج إلى المتجر والتسويق والعميل وتطوير العمل.", icon: Store, href: "/ecommerce" },
  { title: "التسويق الإلكتروني", text: "افهم الجمهور والرسالة والمحتوى والتحويل بصورة عملية.", icon: Target, href: "/marketing" },
  { title: "صناعة المحتوى", text: "حوّل أفكارك إلى محتوى منتظم ومفيد يدعم مسارك.", icon: PenTool, href: "/paths" },
  { title: "الذكاء الاصطناعي", text: "استخدم AI لدعم البحث والإنتاجية والمحتوى والتسويق.", icon: Bot, href: "/paths" },
  { title: "العمل والمشروع الرقمي", text: "ابنِ مهارة وتطبيقًا وخبرة قبل البحث عن الفرصة التالية.", icon: BriefcaseBusiness, href: "/opportunities" },
];

const quizOptions = [
  { value: "work-from-phone", label: "أريد فهم فرصة العمل الرقمي", path: "فرصة العمل الرقمي", reason: "لأن البداية الآمنة هي فهم المجال والمهارات والالتزامات قبل اتخاذ أي قرار." },
  { value: "marketing", label: "أريد تعلم التسويق الإلكتروني", path: "مسار التسويق الإلكتروني", reason: "لأنك تريد فهم الجمهور والرسالة والمحتوى والقنوات الرقمية." },
  { value: "products", label: "أريد فهم التجارة الإلكترونية", path: "مسار التجارة الإلكترونية", reason: "لأنك تحتاج خريطة من المنتج إلى المتجر والتسويق والعميل." },
  { value: "content", label: "أريد صناعة محتوى", path: "مسار صناعة المحتوى", reason: "لأنك تريد بناء ممارسة مفيدة ومنتظمة حول الفكرة والجمهور." },
  { value: "ai", label: "أريد استخدام الذكاء الاصطناعي", path: "مسار الذكاء الاصطناعي العملي", reason: "لأنك تبحث عن أداة تدعم التعلم والإنتاجية والتسويق." },
  { value: "unsure", label: "لا أعرف بعد من أين أبدأ", path: "أساسيات العالم الرقمي", reason: "لأن البداية الأفضل هي فهم المجالات واختيار مهارة أولى بهدوء." },
] as const;

const primaryNav = [
  ["فرصة العمل", "/opportunities"], ["كيف تبدأ؟", "/start"], ["التسويق الإلكتروني", "/marketing"], ["التجارة الإلكترونية", "/ecommerce"], ["الأكاديمية", "/academy"], ["المسارات", "/paths"], ["عن أم كنعان", "/about"], ["المدونة", "/blog"],
] as const;

export default function Home() {
  const { user, isAuthenticated } = useAuth();
  const track = trpc.platform.analytics.track.useMutation();
  const recommend = trpc.platform.discovery.recommend.useMutation();
  const editableCta = trpc.platform.public.contentBlock.useQuery({ blockKey: "homepage_primary_cta" });
  const [selectedQuiz, setSelectedQuiz] = useState<(typeof quizOptions)[number] | null>(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  useEffect(() => { track.mutate({ eventType: "page_view", source: "home" }); }, []);
  const trackCta = (source: string) => track.mutate({ eventType: "cta_click", source });
  const trackWhatsApp = (source: string) => { track.mutate({ eventType: "whatsapp_click", source }); trackCta(`whatsapp_${source}`); };
  const handleQuiz = (option: (typeof quizOptions)[number]) => { setSelectedQuiz(option); recommend.mutate({ goal: option.value, answers: { primaryGoal: option.value }, sessionKey: crypto.randomUUID() }); track.mutate({ eventType: "discovery_completed", source: "home_quiz", metaJson: JSON.stringify({ goal: option.value }) }); };
  const primaryCtaText = editableCta.data?.body || "اكتشف كيف تبدأ";

  return <div className="hamdan-page" dir="rtl">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "EducationalOrganization", name: "منصة أم كنعان الرقمية", alternateName: "منصة أم كنعان الرقمية", description: "منصة عربية للتعلم والتطبيق في العمل الرقمي والتسويق والتجارة الإلكترونية.", inLanguage: "ar" }) }} />
    <header className="site-header"><div className="hamdan-container header-inner"><a className="brand" href="#top" aria-label="الانتقال إلى بداية منصة أم كنعان الرقمية"><img className="brand-mark" src="/manus-storage/hamdan-digital-logo-mark_978b9af8.png" alt="" /><span className="brand-name"><strong>منصة أم كنعان الرقمية</strong><span>منصة أم كنعان الرقمية</span></span></a><nav className="site-nav" aria-label="التنقل الرئيسي">{primaryNav.map(([label, href]) => <a href={href} key={href}>{label}</a>)}</nav><div className="header-actions">{isAuthenticated ? <Link className="login-link" href="/account">{user?.name?.split(" ")[0] ?? "حسابي"}</Link> : <button className="login-link" onClick={startLogin}>تسجيل الدخول</button>}<a className="header-cta" target="_blank" rel="noreferrer" href={whatsappHref(WHATSAPP_MESSAGES.generalPath)} onClick={() => trackWhatsApp("header_contact")}>تحدث مع أم كنعان <MessageCircle size={14} /></a><button className="mobile-menu-button" aria-label={mobileMenuOpen ? "إغلاق القائمة" : "فتح القائمة"} onClick={() => setMobileMenuOpen(v => !v)}>{mobileMenuOpen ? <X size={20} /> : <Menu size={21} />}</button></div></div></header>
    {mobileMenuOpen && <div className="mobile-nav" role="dialog" aria-label="قائمة التنقل"><div className="mobile-nav-panel"><div className="mobile-nav-top"><strong>تصفح المنصة</strong><button onClick={() => setMobileMenuOpen(false)} aria-label="إغلاق القائمة"><X size={20} /></button></div>{primaryNav.map(([label, href]) => <a href={href} key={href} onClick={() => setMobileMenuOpen(false)}>{label}<ChevronLeft size={17} /></a>)}<a className="button-primary mobile-nav-cta" target="_blank" rel="noreferrer" href={whatsappHref(WHATSAPP_MESSAGES.generalPath)} onClick={() => trackWhatsApp("mobile_nav_contact")}><MessageCircle size={17} /> تحدث مع أم كنعان</a><Link className="mobile-shop-link" href="/shop" onClick={() => setMobileMenuOpen(false)}>الموارد الرقمية (اختياري)</Link></div><button className="mobile-nav-scrim" aria-label="إغلاق القائمة" onClick={() => setMobileMenuOpen(false)} /></div>}
    <main id="top"><section className="hero" aria-labelledby="hero-title"><div className="hamdan-container hero-grid"><div className="hero-copy"><span className="eyebrow">هاتفك يمكن أن يكون بداية فرصتك الرقمية</span><h1 id="hero-title" className="hero-title hamdan-display">تعلّم. طبّق. سوّق. <em>وابنِ مهارتك.</em></h1><p>تعلّم التجارة الإلكترونية والتسويق الإلكتروني وصناعة المحتوى واستخدام أدوات الذكاء الاصطناعي، ثم اكتشف كيف تطور مهارة وبناء فرصة في العالم الرقمي.</p><div className="hero-actions"><a className="button-primary" href="#how-start" onClick={() => trackCta("hero_discover_start")}><Rocket size={18} /> {primaryCtaText}</a><a className="button-light" target="_blank" rel="noreferrer" href={whatsappHref(WHATSAPP_MESSAGES.opportunity)} onClick={() => trackWhatsApp("hero_opportunity")}><MessageCircle size={18} /> تحدث مع أم كنعان</a></div><div className="hero-note"><ShieldCheck size={17} /><span>لا توجد أرباح أو وظيفة مضمونة. تبدأ الفرصة بفهم المجال وبناء مهارة وتطبيقها.</span></div></div><div className="hero-visual" aria-label="صورة توضيحية للتعلم الرقمي من الهاتف"><img className="hero-image" src="/manus-storage/hamdan-digital-hero-reference_490dc317.png" alt="تعلم مهارات رقمية من الهاتف" /><div className="hero-card"><small>مسارك العملي</small><strong>هاتف ← مهارة ← تطبيق</strong><div className="hero-card-route"><i /><i /><i /><i /></div></div></div></div></section>
      <section className="hook-band"><div className="hamdan-container"><div className="hook-inner"><div><strong>منصة أم كنعان الرقمية ليست متجرًا ولا وعدًا سريعًا.</strong><p>هي منصة لفهم العمل الرقمي وتعلّم مهارة وتطبيقها وتسويقها، ثم الحديث بوضوح عن الفرص المناسبة.</p></div><div className="hook-formula"><span>هاتف</span><span>مهارة</span><span>تطبيق</span><span>تسويق</span><span>فرصة</span></div></div></div></section>
      <section className="section section-soft" id="how-start"><div className="hamdan-container problem-grid"><div className="section-heading"><span className="eyebrow">كيف تبدأ؟</span><h2 className="hamdan-display">ابدأ بفهم العالم الرقمي، لا بشراء أدوات أو مطاردة وعود.</h2><p>اختر مجالًا واحدًا، تعلّم أساسه، نفّذ تمرينًا، ثم قيّم ما تعلمته قبل الانتقال للخطوة التالية.</p><Link className="text-route-link" href="/start">شاهد خطوات البداية <ArrowLeft size={16} /></Link></div><div><div className="problem-note"><strong>الفرصة تحتاج وضوحًا قبل الحماس.</strong><p>ستعرف ما الذي تحتاجه، ما الذي ستتعلمه، وما الذي لا نعد به قبل أي التزام أو قرار مالي.</p></div><div className="problem-list">{["حدّد هدفك ومهارتك الأولى.", "تعلّم أساسًا عمليًا من مسار واحد.", "طبّق مشروعًا أو تمرينًا صغيرًا.", "افهم كيف تصل إلى جمهور أو عميل.", "اسأل عن الفرصة والتفاصيل بوضوح."].map((item, index) => <div className="problem-item" key={item}><span className="problem-index">0{index + 1}</span>{item}</div>)}</div></div></div></section>
      <section className="section"><div className="hamdan-container"><div className="section-heading"><span className="eyebrow">ماذا ستتعلم؟</span><h2 className="hamdan-display">خمسة محاور تبني فهمك وتطبيقك.</h2><p>المتجر والمنتجات الرقمية أدوات مساندة عند الحاجة، لكن البداية هي التعلم والتطبيق وفهم السوق.</p></div><div className="fields-grid core-fields-grid">{fields.map(({ title, text, icon: Icon, href }) => <Link className="field-card" href={href} key={title}><span className="field-icon"><Icon size={20} /></span><h3>{title}</h3><p>{text}</p><span className="field-link">استكشف المجال <ChevronLeft size={15} /></span></Link>)}</div></div></section>
      <section className="section video-section"><div className="hamdan-container video-grid"><div><span className="eyebrow">فيديو تعريفي</span><h2 className="hamdan-display">شاهد كيف تبدأ رحلتك الرقمية.</h2><p>فيديو قصير سيشرح فكرة منصة أم كنعان الرقمية والمسارات التي يمكنك البدء من خلالها. المساحة جاهزة لإضافة YouTube أو رابط استضافة أو ملف فيديو حقيقي لاحقًا.</p></div><div className="video-placeholder" role="region" aria-label="مكان الفيديو التعريفي"><span className="video-placeholder-icon"><Play size={24} /></span><strong>ما هي منصة أم كنعان الرقمية؟</strong><small>أضف مصدر الفيديو المعتمد من لوحة المحتوى عند توفره.</small></div></div></section>
      <section className="section section-ink"><div className="hamdan-container"><div className="section-heading"><span className="eyebrow">من الهاتف إلى الفرصة</span><h2 className="hamdan-display">هاتف → مهارة → تطبيق → تسويق → فرصة.</h2><p>لا توجد طريقة سحرية. العمل الرقمي يحتاج إلى تعلّم وتطبيق وصبر وفهم للسوق.</p></div><div className="path-story">{[["01", "تعلّم", "افهم الأساسيات التي تخدم هدفك."], ["02", "طبّق", "نفّذ تمرينًا أو مشروعًا صغيرًا."], ["03", "سوّق", "تعلّم الوصول إلى الجمهور والعميل."], ["04", "طوّر", "حسّن مهارتك من التجربة والتغذية الراجعة."], ["05", "اكتشف الفرصة", "اسأل عن التفاصيل قبل أي قرار." ]].map(([number, title, text]) => <article className="path-step" key={number}><span className="path-step-number">{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
      <section className="section opportunity-brief" id="opportunity"><div className="hamdan-container"><div className="section-heading"><span className="eyebrow">فرصة العمل الرقمي</span><h2 className="hamdan-display">افهم طبيعة الفرصة قبل أن تقرر.</h2><p>عند الاستفسار، يجب أن تُشرح طبيعة النموذج والجهة أو الشركة المرتبطة والمنتجات أو الخدمات والرسوم والالتزامات وعدم ضمان الأرباح بوضوح.</p></div><div className="transparency-grid"><article><CircleAlert size={21} /><h2>ما هي الفرصة؟</h2><p>فرصة للتعلم والتطبيق وبناء مهارات في التجارة والتسويق الرقمي، وليست وظيفة أو دخلًا مضمونًا.</p></article><article><ClipboardList size={21} /><h2>ماذا تحتاج؟</h2><p>وقتًا للتعلم، تطبيقًا منتظمًا، وفهمًا للمنتج والسوق قبل اتخاذ أي التزام.</p></article><article><ShieldCheck size={21} /><h2>ماذا لا نعد به؟</h2><p>لا توجد أرباح مضمونة ولا وظيفة مضمونة ولا وعود مالية غير واقعية.</p></article></div><div className="split-cta"><Link className="button-secondary" href="/opportunities">اقرأ تفاصيل الفرصة <ArrowLeft size={17} /></Link><a className="button-primary" target="_blank" rel="noreferrer" href={whatsappHref(WHATSAPP_MESSAGES.opportunity)} onClick={() => trackWhatsApp("opportunity_brief")}><MessageCircle size={18} /> اسأل عن تفاصيل الفرصة</a></div></div></section>
      <section className="section section-soft" id="quiz"><div className="hamdan-container"><div className="quiz-wrap"><div className="quiz-copy"><span className="eyebrow">اختبار بسيط</span><h2 className="hamdan-display">اكتشف نقطة البداية الأقرب لك.</h2><p>اختر هدفك الحالي. سنقترح بداية مبررة، ثم يمكنك مناقشتها مع أم كنعان.</p></div><div className="quiz-options">{selectedQuiz ? <div className="quiz-result"><small>المسار المقترح لك</small><strong>{selectedQuiz.path}</strong><p>{selectedQuiz.reason}</p><a target="_blank" rel="noreferrer" href={whatsappHref(`السلام عليكم الأستاذة أم كنعان، ظهر لي أن المسار المقترح لي هو: ${selectedQuiz.path}. أريد معرفة كيف أبدأ.`)} onClick={() => trackWhatsApp("quiz_result")}>ناقش المسار مع أم كنعان <ArrowLeft size={15} /></a></div> : quizOptions.map(option => <button className="quiz-option" key={option.value} onClick={() => handleQuiz(option)}>{option.label}<ArrowUpLeft size={17} /></button>)}</div></div></div></section>
      <section className="section" id="academy"><div className="hamdan-container"><div className="section-heading"><span className="eyebrow">أكاديمية أم كنعان</span><h2 className="hamdan-display">الأكاديمية تدعم الرحلة؛ لا تستبدل التطبيق.</h2><p>المستوى المتاح حاليًا هو «أساسيات العالم الرقمي». وتظهر المستويات التالية بوضوح كخطة قادمة حتى يكتمل محتواها.</p></div><div className="academy-grid"><Link className="academy-card" href="/academy/digital-work-foundations"><span className="tag">متاح الآن</span><h3>المستوى 1: أساسيات العالم الرقمي</h3><p>دروس قصيرة وتمارين واختبار تمهيدي لمن يريد بناء بداية منظمة.</p><div className="card-foot"><span>ابدأ الآن</span><ArrowLeft size={16} /></div></Link>{[["المستوى 2: التسويق الإلكتروني", "قريبًا بعد اعتماد الدروس والتطبيقات الفعلية."], ["المستوى 3: التجارة الإلكترونية", "قريبًا بعد اعتماد المحتوى العملي والمتطلبات." ]].map(([title, text]) => <article className="academy-card" key={title}><span className="tag">قريبًا</span><h3>{title}</h3><p>{text}</p><div className="card-foot"><span>مسار قيد الإعداد</span><GraduationCap size={16} /></div></article>)}</div><div className="split-cta"><Link className="button-secondary" href="/academy">شاهد الأكاديمية <ArrowLeft size={17} /></Link><a className="button-primary" target="_blank" rel="noreferrer" href={whatsappHref(WHATSAPP_MESSAGES.academy)} onClick={() => trackWhatsApp("academy_home")}>اسأل عن التدريب <MessageCircle size={18} /></a></div></div></section>
      <section className="section section-soft"><div className="hamdan-container trust-grid"><article className="trust-statement"><span className="eyebrow">الشفافية</span><h2 className="hamdan-display">نحن لا نبيع لك حلمًا.</h2><p>العمل الرقمي يحتاج إلى تعلم وتطبيق وصبر وفهم للسوق. لا توجد طريقة سحرية، ولا أرباح مضمونة، ولا وظيفة مضمونة. هدفنا أن تساعدك على فهم المجال وتطوير مهاراتك واتخاذ قرارك بناءً على معرفة واضحة.</p></article><div className="trust-points"><article className="trust-point"><ShieldCheck size={21} /><div><h3>وضوح قبل الالتزام</h3><p>تظهر التكاليف والمتطلبات والتحديات الواقعية قبل أي قرار مالي.</p></div></article><article className="trust-point"><Lightbulb size={21} /><div><h3>تعلم قابل للتطبيق</h3><p>كل خطوة تربط المعرفة بتمرين أو مشروع أو قرار أوضح.</p></div></article><article className="trust-point"><CheckCircle2 size={21} /><div><h3>السوق جزء من الرحلة</h3><p>المهارة لا تنفصل عن فهم العميل والقيمة والتسويق المستمر.</p></div></article></div></div></section>
      <section className="final-cta"><div className="hamdan-container final-inner"><span className="eyebrow">خطوتك التالية</span><h2 className="hamdan-display">تعلّم بوضوح، ثم <em>تواصل بوعي.</em></h2><p>ابدأ بمسار أو اسأل أم كنعان عن الفرصة أو التسويق أو التجارة الإلكترونية حسب هدفك.</p><div className="final-actions"><a className="button-primary" target="_blank" rel="noreferrer" href={whatsappHref(WHATSAPP_MESSAGES.generalPath)} onClick={() => trackWhatsApp("final_general")}> <MessageCircle size={18} /> تحدث مع أم كنعان</a><Link className="button-light" href="/paths"><Compass size={18} /> استكشف المسارات</Link></div></div></section>
    </main><footer className="site-footer"><div className="hamdan-container footer-inner"><div className="footer-brand"><img src="/manus-storage/hamdan-digital-logo-mark_978b9af8.png" alt="" /> منصة أم كنعان الرقمية</div><div className="footer-links"><a href="/opportunities">فرصة العمل</a><a href="/marketing">التسويق الإلكتروني</a><a href="/ecommerce">التجارة الإلكترونية</a><a href="/academy">الأكاديمية</a><a href="/blog">المدونة</a><a href="/shop">الموارد الرقمية</a><a href="/privacy">الخصوصية</a></div><p className="footer-disclaimer">المحتوى تعليمي، ولا توجد ضمانات للربح أو النجاح. تختلف النتائج حسب المهارة والجهد والسوق وطريقة التطبيق.</p></div></footer><a className="whatsapp-float" target="_blank" rel="noreferrer" href={whatsappHref(WHATSAPP_MESSAGES.generalPath)} onClick={() => trackWhatsApp("floating_button")}><MessageCircle size={19} /> تحدث مع أم كنعان</a>
  </div>;
}
